apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: python-hello-world-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: python-hello-world
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Object
    object:
      metric:
        name: http_requests_rate
      describedObject:
        apiVersion: v1
        kind: Service
        name: python-hello-world-service
      target:
        type: Value
        value: "10"